pkg/controller/lifecycle/actuator.go
This PR explicitly states that service account tokens will not be mounted for the OWA pods running in the seed cluster.
Fixes #
```other operator
Service account tokens for the `oidc-webhook-authenticator` pods will no longer be automounted.
```
=> Do not automount service account tokens for the OWA pods

.ci/pipeline_definitions
My guess is that this was overwriting the base definition and this is why the `verify` step is not called on release.
Fixes #
```feature user
```
=> Call verify step on release

.dockerignore, Makefile, cmd/gardener-extension-shoot-oidc-service/app/app.go, vendor/k8s.io/component-base/version/verflag/verflag.go, vendor/modules.txt
This PR adds support for `--version` flag.
Fixes #
```feature operator
`--version` flag is added to display the binary/component version and metadata.
```
=> Add support for `--version` flag

.test-defs/lifecycle.yaml, Dockerfile
Bumps go version to 1.17.8
Fixes #
```other operator
Shoot oidc service extension is now built using `golang:1.17.8`.
```
=> Bump go version to 1.17.8

pkg/controller/lifecycle/actuator.go
After vendoring g/g v1.43.2 a regression was introduced. This resulted in secrets with data keys of `.crt` and `.key` instead of `oidc-webhook-authenticator-tls.crt` and `oidc-webhook-authenticator-tls.key`. This PR fixes the name generation of the data keys. [reference](https://github.com/gardener/gardener/commit/6733cbb518020c931a3aab656750555483137f18#diff-3c51a57fca1f8609e5aa852f54d34b3cbfadf2e255b21b00877f70f033893ed8R146)
Fixes #
```feature user
NONE
```
=> Fix name of generated tls secret data

test/e2e/common_test.go, test/e2e/create_enable_delete_test.go, test/e2e/create_enable_disable_delete_test.go, test/e2e/create_enable_disrupt_reconcile_delete_test.go, test/e2e/create_enable_hibernate_delete_test.go, test/e2e/e2e_suite_test.go
This moves all e2e test to the package `e2e_tests` and also fixes the handling of an error.
Fixes #
```feature user
NONE
```
=> Move e2e tests to a single package

.test-defs/lifecycle.yaml, Dockerfile
Update golang and alpine versions
- golang to 1.17.9
- alpine to 3.15.4
Fixes #
```other operator
The golang version has been updated to 1.17.9.
```
```other operator
The alpine version has been updated to 3.15.4.
```
=> Update golang and alpine versions

.test-defs/lifecycle.yaml, Dockerfile
Upgrade go version to 1.17.11.
Fixes #
```operator other
The extension is now built using `golang:1.17.11`.
```
=> Upgrade go to version 1.17.11

.docforge/manifest.yaml
Update manifest file
```doc developer
NONE
```
=> Remove go templates from manifest

.test-defs/lifecycle.yaml, Dockerfile
Fixes #
```other operator
The extension is now built using go version `1.18.6`.
```
=> Update go version to 1.18.6

go.mod, pkg/controller/lifecycle/actuator.go
This PR updates the version of `HorizontalPodAutoscaler` from `v2beta1` to `v2` when Seed k8s is >= 1.23. This change was needed since `v2beta1` will become deprecated in 1.26 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26
Fixes #
`v2` of `HorizontalPodAutoscaler` cannot be used in versions of k8s < 1.23. When 1.23 becomes the minimal version for our Seeds this `if` statement will be removed and we will be using only `v2`
```other operator
`HorizontalPodAutoscaler` now uses v2 when seed k8s version is >= 1.23
```
=> Update HPA version to v2 if k8s version is >= 1.23

.test-defs/lifecycle.yaml, Dockerfile, go.mod, hack/test-e2e-provider-local.sh
Fixes #
```other operator
The extension is now built using go version `1.19.2`.
```
=> Update go version to 1.19.2

.test-defs/lifecycle.yaml, Dockerfile
Fixes #
```other operator
The extension is now built using go version `1.19.3`.
```
=> Update go version to 1.19.3

pkg/controller/lifecycle/actuator.go, test/e2e/create_enable_hibernate_delete_test.go
This PR fixes a regression introduced when vendoring g/g version containing gardener/gardener#6054.
Fixes #
```bugfix operator
OWA now correctly scales to zero replicas during shoot hibernation.
```
=> Fix scale down during hibernation

.test-defs/lifecycle.yaml, Dockerfile
Updates go version to 1.19.4.
Fixes #
```other operator
The extension is now build using go version `1.19.4`.
```
=> Update go version to 1.19.4

example/10-fake-shoot-controlplane.yaml, example/30-cluster.yaml, hack/api-reference/config.json
Drop support for kubernetes < 1.20 for shoot oidc service extension
Part of https://github.com/gardener/gardener/issues/6911
```other operator
The extension no longer supports Shoots with Кubernetes version < 1.20.
```
=> Drop support for kubernetes < 1.20 for shoot oidc service extension

.ci/pipeline_definitions, Dockerfile, Makefile
Build multi-arch images for amd64 and arm64
Fixes #
```feature user
The docker image of this repository now supports `linux/arm64`.
```
=> Build multi-arch images for amd64 and arm64

.test-defs/lifecycle.yaml, Dockerfile
Bump golang to 1.19.5
Fixes #
```feature operator
The extension is now built using go version `1.19.5`.
```
=> Bump golang to 1.19.5

pkg/controller/lifecycle/actuator.go
Uses constant for ha config type label. Cleanup.
Fixes #
```feature user
NONE
```
=> Use constant for ha config type label

Makefile
Run first `go mod tidy` and then `go mod vendor` like in [gardener's makefile](https://github.com/gardener/gardener/blob/master/Makefile#L196)
```bugfix developer
NONE
```
=> Make revendor command order fix

.test-defs/lifecycle.yaml, Dockerfile, go.mod
Fixes #
```other operator
The extension is now built using go version `1.20.2`.
```
=> Update go version to 1.20.2

cmd/gardener-extension-shoot-oidc-service/app/app.go, cmd/gardener-extension-shoot-oidc-service/app/options.go
Removes unused controller options. Thanks for reporting @Kostov6 !
Fixes #
```feature user
NONE
```
=> Remove unused controller options

go.mod, go.sum, pkg/controller/healthcheck/add.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go, vendor/modules.txt
Cherry-pick of #101 
* Vendor `gardener@1.65.3`
* Add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
Fixes #
```bugfix operator
The stale healthcheck conditions from the `shoot-oidc-service` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```
=> Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove` (#101)

.test-defs/lifecycle.yaml, Dockerfile
Fixes #
```other dependency
The extension is now built using go version `1.20.6`.
```
=> Update go version go 1.20.6

go.mod, pkg/controller/lifecycle/actuator.go
**How to categorize this PR?**
/kind cleanup
Drop support for kubernetes < 1.24 for `shoot-oidc-service` extension.
Part of https://github.com/gardener/gardener/issues/8405
/squash
```breaking operator
The `shoot-oidc-service` extension no longer supports Shoots with Кubernetes version < 1.24.
```
=> Drop support for Shoots with Kubernetes version < 1.24

.test-defs/lifecycle.yaml, Dockerfile
Update golang to 1.21.3
Fixes #
```other operator
This extension is now built using go version 1.21.3
```
=> Update golang to 1.21.3

pkg/controller/lifecycle/actuator.go
Similar to https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/53
```bugfix operator
A bug in the `shoot-oidc-service` controller that was causing the OIDC Webhook Authenticator CA secret for a shoot cluster to be recreated instead of restored during control plane migration has been fixed.  
```
=> Keep secretsmanager secrets in the seed during migration

.ci/prepare_release
Call `prepare_release` with the correct number of arguments https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/810d8c118eb1f01c04856ce304489946a8b48bb9/.ci/hack/prepare_release#L19
Fixes #
```feature user
```
=> Fix call to prepare_release script

.github/dependabot.yaml
A lot of the dependencies of this repo are updated with g/g anyways. This PR basically applies the suggestion from https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/150#discussion_r1476280975
Fixes #
```feature user
NONE
```
=> Dependabot update only g/g dependency

pkg/controller/lifecycle/actuator.go
This PR increases the memory limit of OWA deployment to `1Gi` and also sets GOMAXPROCS & GOMEMLIMIT.
See https://www.riverphillips.dev/blog/go-cfs/ and https://hsleep.medium.com/optimizing-memory-management-in-go-with-gomemlimit-da8ed23e2dcb for motivation on setting the two env variables. 
Fixes #
```feature user
NONE
```
=> Increase mem limit of OWA deployment

pkg/controller/lifecycle/actuator.go
Lower the initial requests used for the OWA deployment.
Fixes #
```other operator
OWA is now deployed with lower cpu and memory requests - 10m and 32Mi respectively.
```
=> Lower cpu and memory requests for OWA

pkg/webhook/kapiserver/webhook.go
Related to https://github.com/gardener/gardener/issues/9864
Fixes #
```feature operator
The extension mutating webhook now uses object selector to reduce the number of calls.
```
=> Add object selector to extension webhook

.github/dependabot.yaml
With this change we should get single PR to update the golang instead of two like
- https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/226, and
- https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/225
Fixes #
```feature user
```
=> [dependabot] Merge two docker ecosystems into one

go.mod, go.sum
Similar motivation as in https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/158
N/A
N/A
```feature user
NONE
```
=> Bump github.com/gardener/gardener from 1.100.0 to 1.100.1

.ci/pipeline_definitions, imagevector/images.yaml
Add  `cloud.gardener.cnudie/responsibles` label
Fixes #
```feature user
```
=> Added Responsibles in images.yaml

hack/oidc-up.sh, pkg/controller/lifecycle/actuator.go, pkg/webhook/kapiserver/ensurer.go, pkg/webhook/kapiserver/mutator_test.go
Simplify controller and mutation flows. Since #173 owa is not authenticating itself in front of the kube-apiserver, therefore the deadlock fixed with #28 cannot happen anymore, i.e. the extension and admission controllers does not have to handle specifically the case when the cluster is hibernated.
Fixes #
```feature user
```
=> Simplify controller and mutation flows

pkg/webhook/kapiserver/ensurer.go, pkg/webhook/kapiserver/mutator_test.go, test/e2e/create_enable_disrupt_reconcile_delete_test.go
Enhance KubeAPIServer ensurer to use container Args instead of Command
Fixes #
```feature user
```
=> Enhance KubeAPIServer ensurer to use container Args instead of Command

example/10-fake-shoot-controlplane.yaml, example/30-cluster.yaml, hack/api-reference/config.json, test/e2e/common_test.go
Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.28.
Part of https://github.com/gardener/gardener/issues/12409
N/A
```feature user
`shoot-oidc-service` no longer supports Shoots with Кubernetes version <= 1.28.
```
=> Drop support for Shoots with Kubernetes version <= 1.28
