.ci/component_descriptor
.ci/pipeline_definitions
.ci/prepare_release
.ci/set_dependency_version
.ci/verify

Add ci pipeline def
Fixes #
```feature user
```

Add ci pipeline def

---

pkg/controller/lifecycle/actuator.go

Prevent hpa from scaling deployments when cluster is hibernated.
Fixes #6 
```feature user
```

Prevent hpa from scaling deployments when cluster is hibernated

---

.ci/component_descriptor

Enhance component descriptor calculation
This should enable automatic update PRs on release of https://github.com/gardener/oidc-webhook-authenticator.
Fixes #
```feature user
```

Enhance component descriptor calculation

---

.docforge/manifest.yaml
docs/installation/installation.md
docs/usage/openidconnects.md

This PR adds documentation files for installation of the service and its usage. Also it adds a [docforge](https://github.com/gardener/docforge) manifest file so that this documentation can be published.
Fixes #
```feature user
```

Add documentation and docforge manifest file

---

Makefile
hack/check-docforge.sh

Adds a step to verify the validity of the docforge manifest files.
Fixes #
```feature user
```

Add check for docforge manifest files

---

Dockerfile

Update golang to 1.16.11 and alpine to 3.13.7
Fixes #
```feature user
```

Update golang to 1.16.11 and alpine to 3.13.7

---

pkg/controller/lifecycle/actuator.go

This PR fixes the control plane migration scenario by preserving the deployed shoot resources.
Fixes #
```bugfix operator
Shoot resources are now preserved during control plane migration.
```

Fix CPM scenario

---

pkg/controller/lifecycle/actuator.go

Increases the CPU limits for the OWA deployment.
Fixes #
```feature user
NONE
```

Increase cpu limits of OWA deployment

---

Makefile
hack/test-e2e-provider-local.sh

This is a dummy step that will be executed on every PR. The real implementation will follow once we have it running in PROW.
Fixes #
```feature user
NONE
```

Add a dummy step to include in prow ci

---

hack/test-e2e-provider-local.sh

This should fix the tests that recently started failing.
Fixes #
```feature user
NONE
```

Change g/g version used for e2e tests

---

hack/test-e2e-provider-local.sh
test/e2e/common_test.go

Pin a newer version of g/g used for test execution.
Fixes #
```feature user
NONE
```

Change g/g version for e2e tests

---

.test-defs/lifecycle.yaml
Dockerfile

Fixes #
```other operator
The extension is now built using go version `1.17.12`.
```

Upgrade go to version 1.17.12

---

Makefile

Cleanup as part of gardener/gardener#6396
Fixes #
```feature user
NONE
```

Remove install-requirements recipe

---

.golangci.yaml
Makefile
pkg/apis/config/v1alpha1/defaults.go
pkg/apis/config/v1alpha1/zz_generated.defaults.go
pkg/cmd/options.go
pkg/constants/constants.go
pkg/controller/lifecycle/actuator.go
pkg/webhook/kapiserver/webhook.go
test/system/lifecycle/lifecycle_test.go

Added linters to ```make check``` and removed go vet command
```feature developer
NONE
```

Added linters to make check

---

hack/test-e2e-provider-local.sh

Fixes #
```feature user
NONE
```

Tests now run against g/g 1.58.0

---

hack/test-e2e-provider-local.sh
test/e2e/common_test.go
test/e2e/create_enable_delete_test.go
test/e2e/create_enable_disable_delete_test.go
test/e2e/create_enable_disrupt_reconcile_delete_test.go
test/e2e/create_enable_hibernate_delete_test.go

Use g/g v1.61.2 for e2e tests
Fixes #
```feature user
NONE
```

Use g/g v1.61.2 for e2e tests

---

.test-defs/lifecycle.yaml
Dockerfile
go.mod

Fixes #
```other operator
This extension is now built using go version `1.20.1`.
```

Update go to version 1.20.1

---

.golangci.yaml
Makefile
pkg/webhook/kapiserver/mutator_test.go

Fixes #
```feature user
NONE
```

Update golangci-lint version to 1.51.1

---

pkg/controller/lifecycle/actuator.go

Fixes #
```bugfix user
A bug preventing OWA to establish trust to a `kube-apiserver` located on the same seed was fixed.
```

Allow OWA to istio-ingressgateway

---

Makefile
hack/oidc-up.sh
pkg/controller/lifecycle/actuator.go

Fixes #
```feature operator
OWA is now scraped by prometheus.
```

Scrape OWA

---

.test-defs/lifecycle.yaml
Dockerfile

Fixes #
```other dependency
This extension is now built using go version `1.20.3`.
```

Update go to version 1.20.3

---

pkg/controller/healthcheck/add.go
pkg/controller/lifecycle/actuator.go
test/e2e/common_test.go
test/system/lifecycle/lifecycle_test.go

Fixes #
```feature user
NONE
```

Clean some TODOs

---

.test-defs/lifecycle.yaml
Dockerfile
hack/generate-kubeconfig.sh
hack/kubeconfig-request.json
hack/test-e2e-provider-local.sh

Fixes #
```other dependency
The extension is now built using go version `1.21.1`.
```

Update go to 1.21.1

---

pkg/controller/lifecycle/actuator.go
pkg/controller/lifecycle/add.go

Fixes #
```feature user
NONE
```

Remove unused clientset

---

.test-defs/lifecycle.yaml
Dockerfile

Fixes #
```other dependency
This extension is now built using go version `1.21.2`.
```

update go to version 1.21.2

---

docs/usage/openidconnects.md

This was somehow missed when the usage docs were written.
Fixes #
```feature user
NONE
```

Add requiredClaims to usage docs

---

docs/operations/deployment.md

This PR replaces an absolute link pointing to the repository with a relative one.
Fixes #
```doc developer
NONE
```

Replaced absolute link with relative

---

.test-defs/lifecycle.yaml

Add apiVersion to test definition

---

Dockerfile

Fixes #
```other dependency
The extension now uses a debian 12 based base image.
```

Update base image to deb12

---

.github/dependabot.yaml
.github/workflows/update_gardener.yaml

Dependabot to update go deps

---

example/local/01-shoot.yaml

Fix sample shoot config for local development
Fixes #
```feature user
NONE
```

Fix sample shoot config for local development

---

.test-defs/lifecycle.yaml
Dockerfile
hack/oidc-up.sh
pkg/controller/lifecycle/actuator.go
pkg/webhook/kapiserver/ensurer.go
pkg/webhook/kapiserver/mutator_test.go

- Clean up a few TODOs
- Update go to version 1.22.5
Fixes #
```other dependency
The extension is now built using go version 1.22.5.
```

Update to go version 1.22.5

---

.ci/pipeline_definitions

Fixing a typo.
Fixes #
```feature user
```

Fix link to SAST enablement PR

---

docs/usage/openidconnects.md

Fixes #
```doc user
Documentation now clarifies when Structured Authentication should be preferred over the Gardener OIDC extension.
```

Clarify documentation regarding Structured Authentication

---

docs/usage/openidconnects.md

This PR improves the usage documentation mentioning a common pitfall.
Fixes #
```feature user
```

Improve usage documentation

---

README.md

**How to categorize this PR?**
/area delivery
/kind cleanup
Similar to https://github.com/gardener/gardener/pull/12632.
```other operator
NONE
```

Add build and go report card badges

---

README.md

This PR fixes broken links in the documentation.
Fixes #
```doc developer
NONE
```

Fixed broken links - 2025.09
